name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    env:
      AFTER_INSTALL_TARGET_DEPENDENCIES: scripts/configure_postgresql.sh
      AFTER_SCRIPT: 'cd $target_ws && rosenv && catkin build $(catkin_topological_order "${TARGET_REPO_PATH}" --only-names) --no-deps --no-status --verbose --make-args roslint'
      CATKIN_LINT: true
      CLANG_FORMAT_VERSION: 3.9
      ROS_REPO: main
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic}
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: melodic, GITHUB_LABEL: clang-format, CLANG_FORMAT_CHECK: file, AFTER_SCRIPT: ""}
          - {ROS_DISTRO: melodic, GITHUB_LABEL: clang-tidy, CLANG_TIDY: true, AFTER_SCRIPT: ""}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
